### ISSUE TITLE
Can't fully login

### ISSUE THREAD

**Issue by ricostuart** [C0ntrolDev/spotify_downloader#15]
I've setup the developer app side of things, and put in the client id and secret. But when I press login and authorise the app, it just keeps spinning the waiting icon on the loading account information section. 
I have managed to download my liked songs, but it won't show up playlists, etc. Unsure if there is a way to see any logs to help?

**Comment by C0ntrolDev** [comment]
Hi. I have a few questions:
1. When you tried to log in to your account in the app did you use the same account as when you created the Spotify service app in spotify developer?
2. What happens when you try to open a playlist page(gives an error, or infinite download)?
3. Am I correct that you can access liked tracks page?

**Comment by C0ntrolDev** [comment]
You can reopen the issue if you provide additional information.

**Comment by NripPrajapat** [comment]
Still can't login.
